#!/usr/bin/env bash

set -eu
set -x

current_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
rm -rf "$current_dir/src/turbulence"
git clone https://github.com/bosh-turbulence/turbulence "$current_dir/src/turbulence"
pushd "$current_dir/src/turbulence"
rm -rf .git*
GO111MODULE=on go mod vendor
./bin/test
popd
