#!/usr/bin/env bash

set -eu
set -x

current_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export GOPATH=$current_dir
pushd "$current_dir/src/turbulence"
rm -rf .git
GO111MODULE=on go mod vendor
popd
